name: publish
on:
  push:
    branches:
      - 'main'
env:
  NODEJS_VERSION: 16
defaults:
  run:
    shell: bash
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Use node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Build Static Web App
        env:
          GITHUB_TOKEN: ${{ secrets.ANTI_GITHUB_RATE_LIMIT_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.ANTI_GITHUB_RATE_LIMIT_USERNAME }}
        run: |
          yarn install --frozen-lockfile --cache-folder .yarn
          yarn build-json
          # CI=false does not let the build fail on warnings
          CI=false yarn build
          echo "awesome-devops.aoepeople.com" > build/CNAME
      - name: Commit Github Pages
        run: |
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'rendered SPA'
        working-directory: ./build
      - name: Push Pages
        uses: ad-m/github-push-action@master
        with:
          directory: build
          branch: gh-pages
          force: true
